### ISSUE TITLE
app ptr map is not locked correctly

### ISSUE THREAD

**Issue by froydnj** [shravanrn/rlbox_api#10]
The code for maintaining app ptrs:

https://github.com/shravanrn/rlbox_api/blob/47e71386c5b83829cc1fdcbd244fcb669248ba65/rlbox.h#L1938-L1964

locks the map on update, but doesn't lock the map on lookups.  The same issue can be seen elsewhere:

https://github.com/shravanrn/rlbox_api/blob/47e71386c5b83829cc1fdcbd244fcb669248ba65/rlbox.h#L1073-L1083
https://github.com/shravanrn/rlbox_api/blob/47e71386c5b83829cc1fdcbd244fcb669248ba65/rlbox.h#L1894-L1905

The lock associated with the map should be taken regardless of whether the map is being modified or merely being read.  `std::map` is not guaranteed to be thread-safe.

**Comment by shravanrn** [comment]
Nice timing :smile:  - I had just written some concurrency tests on a separate branch and had just run into this a couple of days ago. Will fix shortly

**Comment by shravanrn** [comment]
Fixed
