### ISSUE TITLE
tainted<T, Sandbox> specializations do not define operator&

### ISSUE THREAD

**Issue by froydnj** [shravanrn/rlbox_api#7]
This behavior is different from the specializations of `tainted_volatile` and from the normal definition of `tainted`, so I believe this is an oversight.

**Comment by froydnj** [comment]
OK, so maybe this isn't an oversight, because if you define a naive `operator&`, then you run into problems copying structs that are laid out like:

```C
struct a {
  int x;
};

struct b {
  struct a object0;
  struct a object1;
};
```

and then the `helper_fieldCopy*` macros don't work correctly, because `&obj.field` doesn't hand back a `tainted<T, Sandbox>*`, but a `tainted<T*, Sandbox>`, which is not quite the same thing.

**Comment by froydnj** [comment]
OK, so maybe this isn't an oversight, because if you define a naive `operator&`, then you run into problems copying structs that are laid out like:

```C
struct a {
  int x;
};

struct b {
  struct a object0;
  struct a object1;
};
```

and then the `helper_fieldCopy*` macros don't work correctly, because `&obj.field` doesn't hand back a `tainted<T, Sandbox>*`, but a `tainted<T*, Sandbox>`, which is not quite the same thing.

**Comment by shravanrn** [comment]
So trying to understand your example here. 
As of a week ago, I fixed a bug where the tainted_volatile struct specializations were missing operator&
In general, only tainted_volatile<T> would define operator&. tainted<T> relies on the default operation of operator&
So right now I think things are as they should be. Please reopen the issue if you have questions, or you think there may be a bug
